### ISSUE TITLE
Set Alarm Notifications

### ISSUE THREAD

**Issue by smvdheijden** [OSGP/Platform#126]
### Story: Set Alarm Notifications
```
As grid operator
I want OSGP to be able to enable/disable the alarm notifications on devices
So that I can control for which alarms to receive a notification from the device
```
#### Scenario: set power up alarm on/off
```
Given a set power up alarm request from a client
When the request is received
Then a response with correlation id should be sent to client
And a set power up alarm command should be sent to the meter
And a meter command executed notification should be sent to the client
```

#### Alternative scenarios:
* TBD

#### Exception scenarios:
* TBD

#### Tasks
- [ ] Define acceptance criteria
- [x] Implement scenarios handle set power up alarm ws request in WS adapter
- [x] Implement scenarios handle set power up alarm request message in Domain adapter
- [x] Implement scenarios handle set power up alarm request message in Platform core
- [ ] Implement scenarios handle set power up alarm request message in Protocol adapter
- [x] Implement scenarios handle set power up alarm response message in Platform core
- [x] Implement scenarios handle set power up alarm response message in Domain adapter
- [x] Implement scenarios handle set power up alarm response message in WS adapter
- [ ] Test

#### Scenario: Handle set power up alarm ws request from a client 
```
Given a set power up alarm request from a client
And the request is for a device with id <<<deviceid>>>
And the request contains a single set power up alarm command action
When the request is received
Then a set power up alarm request message should be sent to the smart metering domain adapter
And the message should contain a deviceid <<<deviceid>>>
And the message should contain a single set power up alarm command action
And the message should contain the type of the alarm to be set (=power up alarm)
And the message should contain ON/OFF parameter... 
```
Alternative scenarios:
- Multiple E-meter commands

Exception scenarios:
* TBD

#### Scenario: Handle set power up alarm request message from the smart metering ws adapter
```
Given a set power up alarm request message from the smart metering ws adapter
When the message is received
Then the set power up alarm request message should be sent to the core
And the message should contain the type of the alarm to be set (=power up alarm)
And the message should contain ON/OFF parameter...
```
####  Alternative scenarios: 
* Multiple E-meter commands
#### Exception scenarios:
* Device is not known

#### Scenario: Handle set power up alarm request message from the smart metering domain adapter
```
Given a set power up alarm request message from the smart metering domain adapter
When the message is received
Then the set power up alarm request message should be sent to DLMS protocol adapter
And the message should contain the type of the alarm to be set (=power up alarm)
And the message should contain ON/OFF parameter...
```
#### Alternative scenarios:
* TBD

#### Exception scenarios:
- Organisation is not known
- Organisation is not authorized for the device (E-meter)
- Protocol is not known for the device

#### Scenario: Handle set power up alarm request message from the core
```
Given a set power up alarm request message from the core
When the message is received
Then get the current bit string alarm filter from the meter
And define the new bit string alarm filter (including ‘set power up alarm’ request )
And a request to set the new bit sting should be sent to METER
And the message should contain the new bit string filter
```
#### Alternative scenarios: 
* Multiple E-meter commands

#### Exception scenarios:
* Device is unreachable

#### Scenario: Handle set power up alarm message from the dsmr protocol adapter
```
Given 
When
Then
```
#### Alternative scenarios:
* TBD

#### Exception scenarios:
* TBD

#### Scenario: Handle set power up alarm response message from the core
```
Given
When
Then
```

#### Alternative scenarios:
* TBD

#### Exception scenarios:
* TBD

#### Scenario: Handle set power up alarm response message from the smart metering domain adapter
```    
Given a set power up alarm response message from the smart metering domain adapter
When the message is received
Then a meter command executed notification should be sent to the client
And the notification should contain a correlation id
```
#### Alternative scenarios:
* TBD

#### Exception scenarios:
* TBD
