### ISSUE TITLE
Replace Keys

### ISSUE THREAD

**Issue by smvdheijden** [OSGP/Platform#128]
### Story: Replace keys
```
As a grid operator
I want to be able to replace the keys of a meter
So that I can communicate in a secure manner with the meter 
```

#### Tasks:
- [ ] Define acceptance criteria
- [ ] Implement scenarios handle Replace keys request in WS adapter
- [ ] Implement scenarios handle Replace keys request message in Domain adapter
- [ ] Implement scenarios handle Replace keys request message in Platform core
- [ ] Implement scenarios handle Replace keys request message in Protocol adapter
- [ ] Implement scenarios handle Replace keys response message in Platform core
- [ ] Implement scenarios handle Replace keys response message in Domain adapter
- [ ] Implement scenarios handle Replace keys response message in WS adapter
- [ ] Implement acceptance tests
- [ ] Test

#### Scenarios

Scenario: Handle replace security keys ws request 
```
Given a replace keys request from a client containing device id E9998000014122715
And the current date is 20160105
When the replace keys request is received 
Then a correlation id should be sent to the client 
And the new authentication and encryption keys are generated and stored with
	| device id 	| E9998000014122715 |
	| valid_from 	| 20160105			|
	| valid_to 		| null				|
And the replaced authentication and encryption keys are stored with
	| device id 	| E9998000014122715 |
	| valid_to 		| 20160105			|
And the new keys should be set on the meter
And a notification containing the correlation id should be sent to the client
```

the happy flow is:
```
1) generateKeys
2) store keys in table with empty valid_from
3) lookup current keys in table
4) set current timestamp in valid_to for current keys
5) set keys on device
6) set current timestamp in valid_from for new keys
7) update dlms_device with the new keys: @Column masterKey 
@Column globalEncryptionUnicastKey @Column authenticationKey;

when 5 fails: empty valid_to for current keys and don't execute 6 and 7
```

#### OSGP Function
```
Functie: Replace Keys
Parameters: DeviceIdentification, AuthenticationKey, EncryptionKey, MasterKey
```
#### Device interface
```
See DLMS Blue book:
Security setup (class_id: 64, version: 0)
global_key_transfer and security_activate
```

#### Input:
```
- DeviceIdentification E-meter
- AuthenticationKey, 
- EncryptionKey
- MasterKey
```
 
#### Response:
```
- Meter response (OK, NOK)
```
