### ISSUE TITLE
Set Special Days Table

### ISSUE THREAD

**Issue by smvdheijden** [OSGP/Platform#130]
### Story: Set Special Days
```
As grid operator
I want OSGP to set the special days table on devices
So that tariff switching is working correctly on special days
```
#### Scenario: set special days table on the meter
```
Given a set special days request from a client
When the request is received
Then a response with correlation id should be sent to client
And a set special days command should be sent to the meter
And a meter command executed notification should be sent to the client
```

#### Tasks
- [ ] Define acceptance criteria
- [x] Implement scenarios handle set special days ws request in WS adapter
- [x] Implement scenarios handle set special days request message in Domain adapter
- [x] Implement scenarios handle set special days request message in Platform core
- [x] Implement scenarios handle set special days request message in Protocol adapter
- [x] Implement scenarios handle set special days response message in Platform core
- [x] Implement scenarios handle set special days response message in Domain adapter
- [ ] Implement scenarios handle set special days response message in WS adapter
- [ ] Test

#### Scenario: Handle set special days ws request from a client 

Given a set special days request from a client
And the request is for a device with id <<<deviceid>>>
And the request contains a single set special days command action
When the request is received
Then a set special days request message should be sent to the smart metering domain adapter
And the message should contain a deviceid <<<deviceid>>>
And the message should contain a single set special days command action
And the message should contain a special days ID (for this type meter)...

#### Alternative scenarios:
- Multiple E-meter commands

#### Exception scenarios:
- TBD

#### Scenario: Handle set special days request message from the smart metering ws adapter
```
Given a set special days request message from the smart metering ws adapter
When the message is received
Then the set special days request message should be sent to the core
```

#### Alternative scenarios: 
- Multiple E-meter commands

#### Exception scenarios:
- Device is not known

#### Scenario: Handle set special days request message from the smart metering domain adapter
```
Given 
When
Then
```

#### Alternative scenarios:
- TBD

#### Exception scenarios:
- Organisation is not known
- Organisation is not authorised for the device (E-meter)
- Protocol is not known for the device

#### Scenario: Handle special days request message from the core
```
Given
When
Then
```

#### Alternative scenarios: 
- Multiple E-meter commands

#### Exception scenarios:
- Device is unreachable

#### Scenario: Handle set special days response message from the dsmr protocol adapter
```
Given
When
Then
```

#### Alternative scenarios:
- TBD

#### Exception scenarios:
- TBD

#### Scenario: Handle set special days response message from the core
```
Given
When
Then
```

#### Alternative scenarios:
- TBD

#### Exception scenarios:
- TBD

#### Scenario: Handle set special days response message from the smart metering domain adapter
```
Given a set special days response message from the smart metering domain adapter
When the message is received
Then a meter command executed notification should be sent to the client
And the notification should contain a correlation id
```
#### Alternative scenarios:
- TBD

#### Exception scenarios:
- TBD

**Comment by klvries** [comment]
It works fine now.
Also when try to use a non-existing device-identification
