### ISSUE TITLE
Synchronize time E

### ISSUE THREAD

**Issue by smvdheijden** [OSGP/Platform#149]
### Story: Synchronize time
```
As a grid operator
I want OSGP to synchronize the time on the device
So that the meter will be behaving correctly with respect to the actual time
```

#### Scenario: Synchronize time
```
Given a synchronize time request from a client
When the request is received
Then a response with correlation id should be sent to client
and a synchronize time command should be sent to the meter
And a meter command executed notification should be sent to the client
```
#### Tasks:
- [x] Define acceptance criteria
- [x] Create web service
- [x] Implement scenarios handle synchronize time ws request in WS adapter
- [x] Implement scenarios handle synchronize time request message in Domain adapter
- [x] Implement scenarios handle synchronize time request message in Platform core
- [x] mplement scenarios handle synchronize time request message in Protocol adapter
- [x] Implement scenarios handle synchronize time response message in Platform core
- [x] Implement scenarios handle synchronize time response message in Domain adapter
- [x] Implement scenarios handle synchronize time response message in WS adapter
- [ ] Implement acceptance tests
- [ ] Test

#### Scenario: Handle synchronize time ws request from a client 
```
Given a synchronize time request from a client
And the request is for a device with id <<<deviceid>>>
And the request contains a single synchronize time command action

When the request is received

Then a synchronize time request message should be sent to the smart metering domain adapter
And the message should contain a deviceid <<<deviceid>>>
And the message should contain a single synchronize time commmand action
```
```
Alternative scenarios:
- TBD
```
```
Exception scenarios:
- TBD
```

#### Scenario: Handle synchronize time request message from the smart metering ws adapter
```
Given a synchronize time request message from the smart metering ws adapter

When the message is received

Then the synchronize time request message should be sent to the core
```
```
Alternative scenarios:
- TBD
```
```
Exception scenarios:
- Device is not known
```

#### Scenario: Handle synchronize time request message from the smart metering domain adapter
```
Given
When
Then
```
```
Alternative scenarios:
- TBD
```
```
Exception scenarios:
- Organisation is not known
- Organisation is not authorised for the device
- Protocol is not known for the device
```

#### Scenario: Handle synchronize time request message from the core
```
Given
When
Then
```
```
Alternative scenarios:
- TBD
```
```
Exception scenarios:
- Device is unreachable
```

#### Scenario: Handle synchronize time response message from the dsmr protocol adapter
```
Given
When
Then
```
```
Alternative scenarios:
- TBD
```
```
Exception scenarios:
- TBD
```

#### Scenario: Handle synchronize time response message from the core
```
Given
When
Then
```
```
Alternative scenarios:
- TBD
```
```
Exception scenarios:
- TBD
```

#### Scenario: Handle synchronize time response message from the smart metering domain adapter
```    
Given a synchronize time response message from the smart metering domain adapter
When the message is received
Then a meter command executed notification should be sent to the client
And the notification should contain a correlation id
```
```
Alternative scenarios:
- TBD
```
```
Exception scenarios:
- TBD
```
