### ISSUE TITLE
Retrieve events

### ISSUE THREAD

**Issue by smvdheijden** [OSGP/Platform#150]
### Story: Retrieve events
```
As grid operator
I want OSGP to retrieve events
So that I can view the events
```

#### Scenario: Retrieve events
```
Given a retrieve events request
When the request is received
Then the events should be retrieved
And the events should be temporarily stored
And a meter data retrieved notification should be sent
```

#### Scenario: Retrieve events results
```
Given a retrieve events results request
When the request is received
Then the events result should be sent 
And the temporarily stored events should be deleted
```

#### Tasks:
- [ ] Define acceptance criteria
- [x] Create web services
- [x]  Implement scenarios handle retrieve events ws request in WS adapter
- [x] Implement scenarios handle retrieve events request message in Domain adapter
- [x]  Implement scenarios handle retrieve events request message in Platform core
- [x] Implement scenarios handle retrieve events request message in Protocol adapter
- [x] Implement scenarios handle retrieve events response message in Platform core
- [x] Implement scenarios handle retrieve events response message in Domain adapter
- [x] Implement scenarios handle retrieve events response message in WS adapter
- [x] Implement scenarios handle retrieve events results ws request in WS adapter
- [ ] Test

##### Scenario: Handle retrieve events ws request with a single query action from a client 
```
Given a retrieve events request from a client
And the request is for a device with id <<<deviceid>>>
And the request contains a single events query action
And the query action is of event type <<<eventtype:???>>>
And the query action is for a period from <<<startdate>>> until <<<enddate>>>

When the request is received

Then a retrieve events request message should be sent to the smart metering domain adapter
And the message should contain a deviceid <<<deviceid>>>
And the message should contain a single query action
And the action should be of type ...
And ...
```

##### Alternative scenarios:
- Multiple queries for different event types
- Multiple queries for different periods

##### Exception scenarios:
- TBD

##### Scenario: Handle retrieve events request message from the smart metering ws adapter
```
Given a retrieve events request message from the smart metering ws adapter

When the message is received

Then a retrieve events request message should be sent to the core
```

##### Alternative scenarios:
- Multiple queries for different event types
- Multiple queries for different periods

##### Exception scenarios:
- Device is not known

##### Alternative scenarios:
- TBD

##### Exception scenarios:
- Organisation is not known
- Organisation is not authorised for the device
- Protocol is not known for the device

##### Alternative scenarios:
- Multiple E-meter queries for different event types
- Multiple E-meter queries for different periods

##### Exception scenarios:
- Device is unreachable

##### Alternative scenarios:
- TBD

##### Exception scenarios:
- TBD

##### Alternative scenarios:
- TBD

##### Exception scenarios:
- TBD

##### Scenario: Handle retrieve events response message from the smart metering domain adapter
```    
Given a retrieve events response message from the smart metering domain adapter
When the message is received
Then the events are temporarily stored
And a meter data retrieved notification should be sent to the client
And the notification should contain a correlation id
```

##### Alternative scenarios:
- TBD

##### Exception scenarios:
- TBD

##### Scenario: Handle retrieve events results ws request from a client
```
Given a retrieve events results ws request
And the request contains a correlation id <<<correlationid>>>

When the request is received

Then the temporary events results should be restored 
And a periodic meter results response should be sent to the client
And the response should contain correlation id <<<correlationid>>>
And the response should contain the events results
And the temporarily stored events should be deleted
```

##### Alternative scenarios:
- TBD

##### Exception scenarios:
- TBD

**Comment by kevinsmeets** [comment]
## Example flow with soap-requests and -responses

### Issue the request

Retreive events for a smartmeter by issuing a **FindEventsRequest**:
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.alliander.com/schemas/osgp/common/2014/10" xmlns:ns1="http://www.alliander.com/schemas/osgp/smartmetering/sm-management/2014/10">
   <soapenv:Header>
      <ns:ApplicationName>SoapUI</ns:ApplicationName>
      <ns:UserName>KevinSmeets</ns:UserName>
      <ns:OrganisationIdentification>LianderNetManagement</ns:OrganisationIdentification>
   </soapenv:Header>
   <soapenv:Body>
      <ns1:FindEventsRequest>

	      <!-- One device identification has to be present. -->
	      <ns1:DeviceIdentification>E9998000014122714</ns1:DeviceIdentification>
	      
	      <!--At least 1 FindEventsQuery has to be present. There's no maximum. -->
	      <ns1:FindEventsQuery>
	         <ns1:EventLogCategory>STANDARD_EVENT_LOG</ns1:EventLogCategory>
	         <ns1:From>2015-01-01T00:00:00.000Z</ns1:From>
	         <ns1:Until>2015-09-01T00:00:00.000Z</ns1:Until>
	      </ns1:FindEventsQuery>

	      <ns1:FindEventsQuery>
	         <ns1:EventLogCategory>FRAUD_DETECTION_LOG</ns1:EventLogCategory>
	         <ns1:From>2015-02-01T00:00:00.000Z</ns1:From>
	         <ns1:Until>2015-08-01T00:00:00.000Z</ns1:Until>
	      </ns1:FindEventsQuery>

	      <ns1:FindEventsQuery>
	         <ns1:EventLogCategory>COMMUNICATION_SESSION_LOG</ns1:EventLogCategory>
	         <ns1:From>2015-03-01T00:00:00.000Z</ns1:From>
	         <ns1:Until>2015-07-01T00:00:00.000Z</ns1:Until>
	      </ns1:FindEventsQuery>

	      <ns1:FindEventsQuery>
	         <ns1:EventLogCategory>M_BUS_EVENT_LOG</ns1:EventLogCategory>
	         <ns1:From>2015-04-01T00:00:00.000Z</ns1:From>
	         <ns1:Until>2015-06-01T00:00:00.000Z</ns1:Until>
	      </ns1:FindEventsQuery>
	      
      </ns1:FindEventsRequest>
   </soapenv:Body>
</soapenv:Envelope>
```

**FindEventsAsyncResponse** for the request:
```
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Header/>
   <SOAP-ENV:Body>
      <ns2:FindEventsAsyncResponse xmlns:ns2="http://www.alliander.com/schemas/osgp/smartmetering/sm-management/2014/10" xmlns:ns3="http://www.alliander.com/schemas/osgp/common/2014/10">
         <ns2:AsyncResponse>

            <ns3:CorrelationUid>LianderNetManagement|||E9998000014122714|||20150929121422784</ns3:CorrelationUid>
            <ns3:DeviceId>E9998000014122714</ns3:DeviceId>

         </ns2:AsyncResponse>
      </ns2:FindEventsAsyncResponse>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

Logging for the above:
12:14:22.546 [ajp-bio-8009-exec-1] INFO  (SmartMeteringManagementEndpoint.java:73) c.a.o.a.w.s.e.SmartMeteringManagementEndpoint - Find events request for organisation: LianderNetManagement and device: E9998000014122714.
12:14:22.675 [ajp-bio-8009-exec-1] INFO  (ManagementService.java:77) c.a.o.a.w.s.a.s.ManagementService - findEvents called with organisation LianderNetManagement
12:14:22.785 [ajp-bio-8009-exec-1] INFO  (SmartMeteringRequestMessageSender.java:79) c.a.o.a.w.s.i.j.SmartMeteringRequestMessageSender - Sending message to the smart metering requests queue
12:14:22.852 [domainSmartMeteringIncomingWebServiceRequestMessageListenerContainer-1] INFO  (WebServiceRequestMessageListener.java:41) c.a.o.a.d.s.i.j.w.WebServiceRequestMessageListener - Received message of type: FIND_EVENTS
12:14:22.947 [domainSmartMeteringIncomingWebServiceRequestMessageListenerContainer-1] INFO  (FindEventsRequestMessageProcessor.java:63) c.a.o.a.d.s.i.j.w.m.FindEventsRequestMessageProcessor - Calling application service function: FIND_EVENTS
12:14:22.967 [domainSmartMeteringIncomingWebServiceRequestMessageListenerContainer-1] INFO  (ManagementService.java:57) c.a.o.a.d.s.a.s.ManagementService - findEvents for organisationIdentification: LianderNetManagement for deviceIdentification: E9998000014122714
12:14:23.038 [domainSmartMeteringIncomingWebServiceRequestMessageListenerContainer-1] INFO  (ManagementService.java:72) c.a.o.a.d.s.a.s.ManagementService - Sending request message to core.
12:14:23.121 [DefaultMessageListenerContainer-2] INFO  (DomainRequestMessageListener.java:48) c.a.o.c.i.j.d.DomainRequestMessageListener - Received domain request message of type: FIND_EVENTS for domain: SMART_METERING and domainVersion: 1.0
12:14:23.241 [DefaultMessageListenerContainer-2] INFO  (ProtocolRequestMessageSender.java:42) c.a.o.c.i.j.p.ProtocolRequestMessageSender - Sending protocol request message for device [E9998000014122714] using protocol [DSMR] with version [4.2.2]
12:14:23.249 [DefaultMessageListenerContainer-2] INFO  (ProtocolRequestMessageSender.java:47) c.a.o.c.i.j.p.ProtocolRequestMessageSender - Message sender destination queue: [protocol-dlms.1_0.osgp-core.1_0.requests] for protocol [DSMR] with version [4.2.2]
12:14:23.255 [DefaultMessageListenerContainer-2] INFO  (ProtocolRequestMessageSender.java:55) c.a.o.c.i.j.p.ProtocolRequestMessageSender - Sending request message to protocol requests queue
12:14:23.284 [DefaultMessageListenerContainer-2] INFO  (DomainRequestMessageListener.java:59) c.a.o.c.i.j.d.DomainRequestMessageListener - Domain request for device [E9998000014122714] processed.
12:14:23.304 [dlmsRequestsMessageListenerContainer-2] INFO  (DeviceRequestMessageListener.java:36) o.o.a.p.d.i.m.DeviceRequestMessageListener - Received message of type: FIND_EVENTS
12:14:23.346 [dlmsRequestsMessageListenerContainer-2] INFO  (ManagementService.java:44) o.o.a.p.d.a.s.ManagementService - findEvents called for device: E9998000014122714 for organisation: LianderNetManagement
12:14:23.353 [dlmsRequestsMessageListenerContainer-2] INFO  (ManagementService.java:49) o.o.a.p.d.a.s.ManagementService - FindEventsQueryMessageDataContainer number of FindEventsQuery: 4
12:14:23.374 [dlmsRequestsMessageListenerContainer-2] INFO  (ManagementService.java:52) o.o.a.p.d.a.s.ManagementService - findEventsQuery.eventLogCategory :STANDARD_EVENT_LOG, findEventsQuery.from: 2015-01-01T01:00:00.000+01:00, findEventsQuery.until: 2015-09-01T02:00:00.000+02:00
12:14:23.396 [dlmsRequestsMessageListenerContainer-2] INFO  (ManagementService.java:52) o.o.a.p.d.a.s.ManagementService - findEventsQuery.eventLogCategory :FRAUD_DETECTION_LOG, findEventsQuery.from: 2015-02-01T01:00:00.000+01:00, findEventsQuery.until: 2015-08-01T02:00:00.000+02:00
12:14:23.405 [dlmsRequestsMessageListenerContainer-2] INFO  (ManagementService.java:52) o.o.a.p.d.a.s.ManagementService - findEventsQuery.eventLogCategory :COMMUNICATION_SESSION_LOG, findEventsQuery.from: 2015-03-01T01:00:00.000+01:00, findEventsQuery.until: 2015-07-01T02:00:00.000+02:00
12:14:23.412 [dlmsRequestsMessageListenerContainer-2] INFO  (ManagementService.java:52) o.o.a.p.d.a.s.ManagementService - findEventsQuery.eventLogCategory :M_BUS_EVENT_LOG, findEventsQuery.from: 2015-04-01T02:00:00.000+02:00, findEventsQuery.until: 2015-06-01T02:00:00.000+02:00
12:14:23.448 [DefaultMessageListenerContainer-1] INFO  (ProtocolResponseMessageListener.java:41) c.a.o.c.i.j.p.ProtocolResponseMessageListener - Received protocol response message with correlationUid [LianderNetManagement|||E9998000014122714|||20150929121422784] and type [FIND_EVENTS]
12:14:23.469 [DefaultMessageListenerContainer-1] INFO  (DeviceResponseMessageService.java:53) c.a.o.c.a.s.DeviceResponseMessageService - Processing protocol response message with correlation uid [LianderNetManagement|||E9998000014122714|||20150929121422784]
12:14:23.477 [DefaultMessageListenerContainer-1] INFO  (DeviceResponseMessageService.java:82) c.a.o.c.a.s.DeviceResponseMessageService - Sending domain response message.
12:14:23.497 [domainSmartMeteringIncomingOsgpCoreResponsesMessageListenerContainer-1] INFO  (OsgpCoreResponseMessageListener.java:41) c.a.o.a.d.s.i.j.c.OsgpCoreResponseMessageListener - Received message of type: FIND_EVENTS
12:14:23.501 [domainSmartMeteringIncomingOsgpCoreResponsesMessageListenerContainer-1] INFO  (FindEventsResponseMessageProcessor.java:70) c.a.o.a.d.s.i.j.c.m.FindEventsResponseMessageProcessor - Calling application service function to handle response: FIND_EVENTS
12:14:23.539 [wsSmartMeteringResponsesMessageListenerContainer-1] INFO  (SmartMeteringResponseMessageListener.java:47) c.a.o.a.w.s.i.j.SmartMeteringResponseMessageListener - Received message of type: FIND_EVENTS
12:14:23.539 [wsSmartMeteringResponsesMessageListenerContainer-1] INFO  (SmartMeteringResponseMessageListener.java:52) c.a.o.a.w.s.i.j.SmartMeteringResponseMessageListener - objectMessage CorrelationUID: LianderNetManagement|||E9998000014122714|||20150929121422784
12:14:23.540 [wsSmartMeteringResponsesMessageListenerContainer-1] INFO  (SmartMeteringResponseMessageListener.java:57) c.a.o.a.w.s.i.j.SmartMeteringResponseMessageListener - Saving events for FIND_EVENTS
12:14:23.562 [wsSmartMeteringResponsesMessageListenerContainer-1] INFO  (FindEventsResponseMessageProcessor.java:77) c.a.o.a.w.s.i.j.m.FindEventsResponseMessageProcessor - Calling application service function to handle response: FIND_EVENTS
12:14:23.562 [wsSmartMeteringResponsesMessageListenerContainer-1] INFO  (FindEventsResponseMessageProcessor.java:82) c.a.o.a.w.s.i.j.m.FindEventsResponseMessageProcessor - Number of events in EventMessageDataContainer: 2
12:14:23.619 [wsSmartMeteringResponsesMessageListenerContainer-1] INFO  (NotificationService.java:48) c.a.o.a.w.s.a.s.NotificationService - sendNotification called with organisation LianderNetManagement
12:14:23.632 [wsSmartMeteringResponsesMessageListenerContainer-1] INFO  (KeyStoreFactoryBean.java:121) o.s.w.s.s.s.KeyStoreFactoryBean - Loading key store from file [/etc/ssl/certs/LianderNetManagement.pfx]
12:14:24.265 [ajp-bio-8009-exec-2] INFO  (SmartMeteringNotificationEndpoint.java:46) c.a.o.s.w.i.w.e.SmartMeteringNotificationEndpoint - Incoming SendNotificationRequest for organisation: LianderNetManagement device: E9998000014122714.
12:14:24.265 [ajp-bio-8009-exec-2] INFO  (NotificationService.java:35) c.a.o.s.w.a.s.NotificationService - Incoming Notification of type: FIND_EVENTS with result: OK


### Get the events

Get the events by issuing a **FindEventsAsyncRequest** containing the correlation UID:
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.alliander.com/schemas/osgp/common/2014/10" xmlns:ns1="http://www.alliander.com/schemas/osgp/smartmetering/sm-management/2014/10">
   <soapenv:Header>
      <ns:ApplicationName>SoapUI</ns:ApplicationName>
      <ns:UserName>KevinSmeets</ns:UserName>
      <ns:OrganisationIdentification>LianderNetManagement</ns:OrganisationIdentification>
   </soapenv:Header>
   <soapenv:Body>
      <ns1:FindEventsAsyncRequest>
         <ns1:AsyncRequest>

            <ns:CorrelationUid>LianderNetManagement|||E9998000014122714|||20150929121422784</ns:CorrelationUid>
            <ns:DeviceId>E9998000014122714</ns:DeviceId>
            
         </ns1:AsyncRequest>
      </ns1:FindEventsAsyncRequest>
   </soapenv:Body>
</soapenv:Envelope>
```

**FindEventsResponse** containing a list of events:
```
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Header/>
   <SOAP-ENV:Body>
      <ns2:FindEventsResponse xmlns:ns2="http://www.alliander.com/schemas/osgp/smartmetering/sm-management/2014/10" xmlns:ns3="http://www.alliander.com/schemas/osgp/common/2014/10">

         <ns2:Events>
            <ns2:timestamp>2015-09-29T14:14:23.421+02:00</ns2:timestamp>
            <ns2:eventType>ALARM_REGISTER_CLEARED</ns2:eventType>
         </ns2:Events>
         <ns2:Events>
            <ns2:timestamp>2015-09-29T14:14:23.421+02:00</ns2:timestamp>
            <ns2:eventType>HARDWARE_ERROR_PROGRAM_MEMORY</ns2:eventType>
         </ns2:Events>

      </ns2:FindEventsResponse>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

Logging for the above:

12:16:52.084 [ajp-bio-8009-exec-1] INFO  (SmartMeteringManagementEndpoint.java:105) c.a.o.a.w.s.e.SmartMeteringManagementEndpoint - Get find events response for organisation: LianderNetManagement and device: E9998000014122714.
12:16:52.085 [ajp-bio-8009-exec-1] INFO  (ManagementService.java:111) c.a.o.a.w.s.a.s.ManagementService - findEventsByCorrelationUid called with organisation LianderNetManagement}
12:16:52.103 [ajp-bio-8009-exec-1] INFO  (ManagementService.java:131) c.a.o.a.w.s.a.s.ManagementService - deleting 1 MeterResponseData rows
12:16:52.107 [ajp-bio-8009-exec-1] INFO  (ManagementService.java:134) c.a.o.a.w.s.a.s.ManagementService - returning a list containing 2 events
12:16:52.140 [ajp-bio-8009-exec-1] INFO  (SmartMeteringManagementEndpoint.java:119) c.a.o.a.w.s.e.SmartMeteringManagementEndpoint - getFindEventsResponse() number of events: 2
12:16:52.141 [ajp-bio-8009-exec-1] INFO  (SmartMeteringManagementEndpoint.java:121) c.a.o.a.w.s.e.SmartMeteringManagementEndpoint - event.eventCode: 11 event.timestamp: 2015-09-29T14:14:23.421+02:00
12:16:52.157 [ajp-bio-8009-exec-1] INFO  (SmartMeteringManagementEndpoint.java:121) c.a.o.a.w.s.e.SmartMeteringManagementEndpoint - event.eventCode: 12 event.timestamp: 2015-09-29T14:14:23.421+02:00
12:16:52.157 [ajp-bio-8009-exec-1] INFO  (SmartMeteringManagementEndpoint.java:123) c.a.o.a.w.s.e.SmartMeteringManagementEndpoint - mapping events to schema type...
12:16:52.160 [ajp-bio-8009-exec-1] INFO  (SmartMeteringManagementEndpoint.java:127) c.a.o.a.w.s.e.SmartMeteringManagementEndpoint - mapping done, sending response...


### No events for the correlation UID

In case there are no events, or the events have been fetched earlier (and thus deleted), an empty list (actually no list at all) will be returned in the **FindEventsResponse**:

```
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Header/>
   <SOAP-ENV:Body>
      <ns2:FindEventsResponse xmlns:ns2="http://www.alliander.com/schemas/osgp/smartmetering/sm-management/2014/10" xmlns:ns3="http://www.alliander.com/schemas/osgp/common/2014/10"/>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

Logging for the above:

12:52:50.287 [ajp-bio-8009-exec-2] INFO  (SmartMeteringManagementEndpoint.java:105) c.a.o.a.w.s.e.SmartMeteringManagementEndpoint - Get find events response for organisation: LianderNetManagement and device: E9998000014122714.
12:52:50.288 [ajp-bio-8009-exec-2] INFO  (ManagementService.java:88) c.a.o.a.w.s.a.s.ManagementService - findEventsByCorrelationUid called with organisation LianderNetManagement}
12:52:50.292 [ajp-bio-8009-exec-2] INFO  (ManagementService.java:109) c.a.o.a.w.s.a.s.ManagementService - deleting 0 MeterResponseData rows
12:52:50.293 [ajp-bio-8009-exec-2] INFO  (ManagementService.java:112) c.a.o.a.w.s.a.s.ManagementService - returning a list containing 0 events
12:52:50.295 [ajp-bio-8009-exec-2] INFO  (SmartMeteringManagementEndpoint.java:119) c.a.o.a.w.s.e.SmartMeteringManagementEndpoint - getFindEventsResponse() number of events: 0
12:52:50.296 [ajp-bio-8009-exec-2] INFO  (SmartMeteringManagementEndpoint.java:123) c.a.o.a.w.s.e.SmartMeteringManagementEndpoint - mapping events to schema type...
12:52:50.296 [ajp-bio-8009-exec-2] INFO  (SmartMeteringManagementEndpoint.java:127) c.a.o.a.w.s.e.SmartMeteringManagementEndpoint - mapping done, sending response...
