### ISSUE TITLE
Retrieve interval data

### ISSUE THREAD

**Issue by smvdheijden** [OSGP/Platform#181]
### Story
```
As a grid operator
I want OSGP to retrieve interval data
So that I can provide the meter data to 3rd parties (who requested the data over P4)
```
#### Tasks:
- [ ] Define acceptance criteria
- [ ] Implement scenarios handle retrieve load profile values ws request in WS adapter
- [ ] Implement scenarios handle retrieve load profile values request message in Domain adapter
- [ ] Implement scenarios handle retrieve load profile values request message in Platform core
- [ ] Implement scenarios handle retrieve load profile values request message in Protocol adapter
- [ ] Implement scenarios handle retrieve load profile values response message in Platform core
- [ ] Implement scenarios handle retrieve load profile values response message in Domain adapter
- [ ] Implement scenarios handle retrieve load profile values response message in WS adapter
- [ ] Implement scenarios handle retrieve load profile values results ws request in WS adapter
- [ ] Implement acceptance tests
- [ ] Test

#### Scenarios

Scenario: Receive a retrieve load profile values request
```
Given a retrieve load profile values request from a client
When the request is received
Then the load profile values should be retrieved from the device
And the load profile values should be temporarily stored
And a load profile values retrieved notification should be sent to the client
```
Scenario: Receive a get load profile values results request
```
Given a get interval values results request from a client for a given period
When the request is received
Then the interval values result should be retrieved from temporary storage
the meter reads should be converted to kWh
(conversion may be done in the scenario above: architecture choice!)
(the unit of the retrieved meter reads is already stored in OSGP )
And a response containing the interval values should be returned to the client
And the temporarily stored interval values should be deleted
```

#### OSGP Functie
```
Functie: Get Actual Meter Reads
Parameters: DeviceIdentification, BeginDate + Timestamp, EndDate + Timestamp
```

#### Device interface
```
Class: 7
ObisCode: 1.0.99.1.0.255
Attribute: 2
Data object:  Please check DLMS object in DLMS en DSMR documentation
{8,0-0:1.0.0.255,2,0}; 
{1,0-0:96.10.2.255,2,0}; 
{3,1-0:1.8.0.255,2,0};
 {3,1-0:2.8.0.255,2,0}
( = clock; AMR profile status E-meter; +A;−A)
```
#### Input:
```
•	PeriodType: Interval (15') (required)
•	DeviceIdentification of the E meter (requiered)
•	Begin period (type: datetime) (requiered)
•	End period (type: datetime) (requiered)
```

#### Response:
```
•	PeriodType: INTERVAL
•	LogTime: datetime
•	ActiveEnergyImportTariffOne: whole number; unit =kWh (conversion to kWh has to be done)
•	ActiveEnergyImportTariffTwo: => always empty for INTERVAL
•	ActiveEnergyExportTariffOne: whole number; unit =kWh (conversion to kWh has to be done)
•	ActiveEnergyExportTariffTwo: => always empty for INTERVAL
•	AMR Profile status code E-meter : has a size of 1 byte
```

**Comment by eduarddrenth** [comment]
adapted xsd
added INTERVAL
Date => BeginDate
added EndDate

adapted all PeriodType and PeriodicMeterReadsRequestData

now translate to protocol adapter

**Comment by SCMHaime** [comment]
@elhachhouchi which load profile values should the interval data contain?

**Comment by rlemmers** [comment]
@elhachhouchi and @SCMHaime, has this question been answered? If not, please do so @elhachhouchi.

**Comment by elhachhouchi** [comment]
@rlemmers and @SCMHaime. This question has been answered and discussed with Sherisse. The returned load profile values are included in the user storie, under the heading 'Response'.
