### ISSUE TITLE
Set configuration object

### ISSUE THREAD

**Issue by smvdheijden** [OSGP/Platform#182]
### Story
```
As grid operator
I want to be able to set the configuration object
So that I can adjust the configuration
```

### Tasks
- [ ] Define acceptance criteria
- [ ] Implement scenarios handle set configuration object request message in WS adapter
- [ ] Implement scenarios handle set configuration object request message in Domain adapter
- [ ] Implement scenarios handle set configuration object request message in Platform core
- [ ] Implement scenarios handle set configuration object request message in Protocol adapter
- [ ] Implement scenarios handle set configuration object response message in Platform core
- [ ] Implement scenarios handle set configuration object response message in Domain adapter
- [ ] Implement scenarios handle set configuration object response message in WS adapter
- [ ] Implement acceptance tests
- [ ] Test

#### Scenarios
Scenario: set M-Bus auto scan off
```
Given a set configuration object request from a client
And the request contains a configuration flag DISCOVER_ON_POWER_ON with value 0
When the request is received
Then a response with correlation id should be sent to client
And a set configuration object command should be sent to the meter
And a command executed notification should be sent to the client
```

#### Platform (WSDL) functie
```
Functie: SetConfigurationObject
Parameters: DeviceIdentification, ConfigurationObject (GprsOperationMode, ConfigurationFlags)
```

#### Device interface
```
Class: 1
ObisCode: 0.1.94.31.3.255
Attribute: 2
Data object: ?
```

**Comment by klvries** [comment]
The code is working fine.

But the story on the board is not updated to the new insights

The issue can be closed
