### ISSUE TITLE
Send an SMS wake up message

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#187]
### Story: Send an SMS wake up message
```
As a Grid Operator
I want to be able to send an SMS message to an E meter
So that I can wake up an E meter for communication
```

#### Tasks:
- [ ] Define acceptance criteria
- [ ] Implement scenarios handle SMS wake up request message
- [ ] Implement acceptance tests
- [ ] Test

#### Scenario: send an SMS wake up request
```
Given true
When a request is received for a device with id 54321
Aad device 54321 uses GPRS for communication (Device has a SIM ICC-ID)
Then call the Jasper Wireless API to send an SMS wake up command to device 54321
And wait for response with status delivered or detect a time out
```

#### Scenario: receive a wake up notification from a meter
```
Given true
When a wake up notification is received from for a device with id 54321
Then send a notification to the requestor.
```
