### ISSUE TITLE
Retrieve actual meter reads

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#188]
### Story
```
As a grid operator
I want OSGP to retrieve actual meter reads
So that I can provide the meter data to 3rd parties (who requested the data over P4)
```

#### Tasks:
- [ ] Define acceptance criteria
- [x] Implement scenarios handle retrieve actual meter reads ws request in WS adapter
- [x] Implement scenarios handle retrieve actual meter reads request message in Domain adapter
- [x] Implement scenarios handle retrieve actual meter reads request message in Platform core
- [x] Implement scenarios handle retrieve actual meter reads request message in Protocol adapter
- [x] Implement scenarios handle retrieve actual meter reads response message in Platform core
- [x] Implement scenarios handle retrieve actual meter reads response message in Domain adapter
- [x] Implement scenarios handle retrieve actual meter reads response message in WS adapter
- [x] Implement scenarios handle retrieve actual meter reads results ws request in WS adapter
- [ ] Implement acceptance tests
- [ ] Test

#### Scenarios

Scenario: Receive a retrieve actual meter reads request
```
Given a retrieve actual meter reads request from a client
When the request is received
Then the actual meter reads should be retrieved from the device
And the actual meter reads should be temporarily stored
And a actual meter reads retrieved notification should be sent to the client
```
Scenario: Receive a get actual meter reads results request
```
Given a get actual meter reads results request from a client
When the request is received
Then the actual meter reads result should be retrieved from temporary storage
And a response containing the actual meter reads should be returned to the client
And the temporarily stored actual meter reads should be deleted
```

#### OSGP Functie
```
Functie: Get Actual Meter Reads
Parameters: DeviceIdentification
```

#### Device interface
```
Class: 3
ObisCode: 1-0:1.8.1.255, 1-0:1.8.2.255, 1-0:2.8.1.255, 1-0:2.8.2.255
Attribute: 2
Data object: 

Output : Meter reads + related timestamp
```
