### ISSUE TITLE
Set administrative status

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#189]
### Story
```
As grid operator
I want to be able to set Administrative Status on or off
So that I can adjust the configuration so that the meter will be (or not) read out via P3
```

#### Tasks:
- [ ] Define acceptance criteria
- [ ] Implement scenarios handle set Administrative Status request in WS adapter
- [ ] Implement scenarios handle set Administrative Status request message in Domain adapter
- [ ] Implement scenarios handle set Administrative Status request message in Platform core
- [ ] Implement scenarios handle set Administrative Status request message in Protocol adapter
- [ ] Implement scenarios handle set Administrative Status response message in Platform core
- [ ] Implement scenarios handle set Administrative Status response message in Domain adapter
- [ ] Implement scenarios handle set Administrative Status response message in WS adapter
- [ ] Implement acceptance tests
- [ ] Test

#### Scenarios

Scenario: Handle set Administrative Status ws request with a single E-meter action from a client 
```
Given a set Administrative Status request from a client
And the request contains a configuration flag ADMINISTRATIVE_STATUS with value X
When the request is received
Then a response with correlation id should be sent to client
And a set Administrative Status command should be sent to the meter
And a command executed notification should be sent to the client
```

#### OSGP Functie
```
Functie: Set Administrative Status
Parameters: DeviceIdentification, ADMINISTRATIVE_STATUS
```

#### Device interface
```
Class: 1
ObisCode: 0.1.94.31.0.255
Attribute: 2
Data object: 
```

#### Output
```
Value = 0: Undefined
Value = 1: Meter is administrative off (Opt Out)
Value = 2: Meter is administrative on (Default)
```

**Comment by SCMHaime** [comment]
@elhachhouchi the scenario above only covers the situation when a request contains a configuration flag with value 0.  Administrative status of 1 is also allowed. What should the result be if the status is equal to 1?

**Comment by SCMHaime** [comment]
@elhachhouchi: What result should be displayed in the smartmeter app?

**Comment by mvhaasteren** [comment]
For testing purtposes.
url = 'https://localhost:443/osgp-adapter-ws-smartmetering/smartMetering/configurationService/'

and message = 
'<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.alliander.com/schemas/osgp/common/2014/10" xmlns:ns1="http://www.alliander.com/schemas/osgp/smartmetering/sm-configuration/2014/10">
   <soapenv:Header>
      <ns:ApplicationName>SOAPUI</ns:ApplicationName>
      <ns:UserName>Maarten</ns:UserName>
      <ns:OrganisationIdentification>LianderNetManagement</ns:OrganisationIdentification>
   </soapenv:Header>
   <soapenv:Body>
      <ns1:SetAdministrativeStatusRequest>
         <ns1:DeviceIdentification>E0004001515495114</ns1:DeviceIdentification>
         <ns1:Enabled>UNDEFINED</ns1:Enabled>
      </ns1:SetAdministrativeStatusRequest>
   </soapenv:Body>
</soapenv:Envelope>'

**Comment by carlogeenen** [comment]
SoapUI testresults so far:

- Get administrative status works fine in Demo App
- Set administrative status works fine in Demo App
- Get administrative status works fine in SoapUI
- Set administrative status does not work correctly in SoapUI
   - GetSetAdministrativeStatusResponse returns:
[Schema Compliance] Expected element 'Description@http://www.alliander.com/schemas/osgp/smartmetering/sm-configuration/2014/10' before the end of the content in element SetAdministrativeStatusResponse@http://www.alliander.com/schemas/osgp/smartmetering/sm-configuration/2014/10
