### ISSUE TITLE
Retrieve administrative status

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#190]
### Story
```
As a grid operator
I want to be able to get administration status of a meter
So that I can see if the meter might  be read out via P3
```

#### Tasks:
- [ ] Define acceptance criteria
- [ ] Implement scenarios handle get administrative status request in WS adapter
- [ ] Implement scenarios handle get administrative status request message in Domain adapter
- [ ] Implement scenarios handle get administrative status request message in Platform core
- [ ] Implement scenarios handle get administrative status request message in Protocol adapter
- [ ] Implement scenarios handle get administrative status response message in Platform core
- [ ] Implement scenarios handle get administrative status response message in Domain adapter
- [ ] Implement scenarios handle get administrative status response message in WS adapter
- [ ] Implement scenarios handle get administrative status result request in WS adapter
- [ ] Implement acceptance tests
- [ ] Test

#### Scenarios

Scenario: get the administrative status from device
```
Given a get administrative status request from a client
And the get administrative status request contains device id <<<deviceid>>>
And the get administrative status request contains organisation id <<<organisationid>>>
And the get administrative status request one single query action
When the get administrative status request is received 
Then a correlation id should be sent to the client 
And a connection with the meter should be established
And the query action should be executed on the meter
And the query action result should be stored
And a notification should be sent to the client
And the notification should contain the correlation id
```

Scenario: Receive a get administrative status result request from the client
```
Given a get administrative status result request from a client
When the request is received
Then the administrative status result should be retrieved from storage
And a response containing the administrative status should be returned to the client
```

#### OSGP Functie
```
Functie: Get Administrative Status
Parameters: DeviceIdentification
```

#### Device interface
```
Class: 1
ObisCode: 0.1.94.31.0.255
Attribute: 2
Data object: 
```

**Comment by klvries** [comment]
It works fine
