### ISSUE TITLE
Read alarm register

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#192]
### Story
```
As a grid operator
I want to be able to read the alarm register from a meter
So that I can and perform relevant actions
```

#### Tasks:
- [ ] Define acceptance criteria
- [x] Implement scenarios handle read the alarm register request in WS adapter
- [x] Implement scenarios handle read the alarm register request message in Domain adapter
- [x] Implement scenarios handle read the alarm register request message in Platform core
- [x] Implement scenarios handle read the alarm register request message in Protocol adapter
- [x] Implement scenarios handle read the alarm register response message in Platform core
- [x] Implement scenarios handle read the alarm register response message in Domain adapter
- [x] Implement scenarios handle read the alarm register response message in WS adapter
- [x] Implement scenarios handle read the alarm register result request in WS adapter
- [ ] Implement acceptance tests
- [ ] Test

#### Scenarios

Scenario: read the alarm register from device
```
Given a read alarm register request from a client
And the read alarm register request contains device id <<<deviceid>>>
And the read alarm register request contains organisation id <<<organisationid>>>
And the read alarm register request one single query action
When the read alarm register request is received 
Then a correlation id should be sent to the client 
And a connection with the meter should be established
And the query action should be executed on the meter
And the query action result should be stored
And a notification should be sent to the client
And the notification should contain the correlation id
```

Scenario: Receive a get alarm register result request from the client
```
Given a get alarm register result request from a client
When the request is received
Then the alarms should be retrieved from storage
And a response containing the alarms should be returned to the client
```
#### OSGP Functie
```
Functie: Get Alarm Register
Parameters: DeviceIdentification
```

#### Device interface
```
Class: 1
ObisCode: 0.0.97.98.0.255 
Attribute: 2
Data object: 
```
