### ISSUE TITLE
Retrieve Configuration

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#193]
### Story
```
As a grid operator
I want to be able to retrieve the configuration of a meter
So that I can check the meter configuration
```

#### Tasks:
- [ ] Define acceptance criteria
- [ ] Implement scenarios handle retrieve configuration request in WS adapter
- [ ] Implement scenarios handle retrieve configuration request message in Domain adapter
- [ ] Implement scenarios handle retrieve configuration request message in Platform core
- [ ] Implement scenarios handle retrieve configuration request message in Protocol adapter
- [ ] Implement scenarios handle retrieve configuration response message in Platform core
- [ ] Implement scenarios handle retrieve configuration response message in Domain adapter
- [ ] Implement scenarios handle retrieve configuration response message in WS adapter
- [ ] Implement scenarios handle retrieve configuration result request in WS adapter
- [ ] Implement acceptance tests
- [ ] Test

#### Scenarios

Scenario: Handle retrieve configuration request
```
Given a retrieve configuration request from a client
And the retrieve configuration request contains device id <<<deviceid>>>
When the retrieve configuration request is received 
Then a correlation id should be sent to the client 
And a connection with the meter should be established
And a list of all available object on the meter should be retrieved
And for each object from the list each authorize attribute should be retrieved
And each retrieved attribute should be stored in the Head-End
And a notification should be sent to the client
And the notification should contain the correlation id
```

Scenario: Handle retrieve configuration results
```
Given a retrieve configuration results request from a client
And the retrieve configuration results request contains device id <<<deviceid>>>
And the retrieve configuration results request contains organisation id <<<organisationid>>>
And the retrieve configuration results request contains correlation id <<<correlationid>>>
When the retrieve configuration results request is received
Then the retrieve configuration results should be retrieved from the storage
And the retrieve configuration results should be sent to the client
```

**Comment by elhachhouchi** [comment]
User story is not yet ready
