### ISSUE TITLE
Set tariffs (Activity Calender - TOU)

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#200]
### Story
```
As grid operator
I want to be able to set tariffs on the E meter
So that In order to register consumption correctly for the different tariffs, in the adequate register
```

#### Tasks:
- [ ] Define acceptance criteria
- [ ] Implement scenarios handle set tariffs request in WS adapter
- [ ] Implement scenarios handle set tariffs request message in Domain adapter
- [ ] Implement scenarios handle set tariffs request message in Platform core
- [ ] Implement scenarios handle set tariffs request message in Protocol adapter
- [ ] Implement scenarios handle set tariffs response message in Platform core
- [ ] Implement scenarios handle set tariffs response message in Domain adapter
- [ ] Implement scenarios handle set tariffs response message in WS adapter
- [ ] Implement acceptance tests
- [ ] Test

#### Scenarios

Scenario: Handle set tariffs ws request with a single E-meter action from a client 
```
Given a set Tariffs request from a client
And the request contains the Activity Calender
And the request contains the activation date
When the request is received
Then a response with correlation id should be sent to client
And a set Tariffs command should be sent to the meter
And a command executed notification should be sent to the client
```

#### OSGP Functie
```
Functie: Set tariffs
Parameters: DeviceIdentification, Activity Calender and Activation Date
```

#### Device interface
```
Class: 20
ObisCode: 0.0.13.0.0.255
Attribute: 2 (Activity Calender)
Attribute: 10 (Activation Date)
Data object: 
```

**Comment by SCMHaime** [comment]
Test has been executed according to the datacombination test technique.

Testcase 1: 1 season, 1 Dayschedule, result: ok
Testcase 2: 4 seasons, 1 Dayschedule, result: ok
Testcase 3: 4 seasons, 2 Dayschedules, result: ok
Testcase 4: 0 seasons, result: ok, validation error (validation test)
Testcase 5: 1 season, 0 Dayschedules, result: ok, validation error (validation test)
Testcase 6: 5 season, result: ok, validation error (negative test)
