### ISSUE TITLE
Retrieve periodic meter reads - GAS

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#225]
### Story
```
As a grid operator
I want OSGP to retrieve periodic meter reads for GAS meter
So that I can provide the meter data to 3rd parties
```

#### Tasks:
- [ ] Define acceptance criteria
- [x] Implement scenarios handle retrieve periodic meter reads for GAS ws request in WS adapter
- [x] Implement scenarios handle retrieve periodic meter reads request for GAS message in Domain adapter
- [x] Implement scenarios handle retrieve periodic meter reads for GAS request message in Platform core
- [x] Implement scenarios handle retrieve periodic meter reads for GAS request message in Protocol adapter
- [x] Implement scenarios handle retrieve periodic meter reads for GAS response message in Platform core
- [x] Implement scenarios handle retrieve periodic meter reads for GAS response message in Domain adapter
- [x] Implement scenarios handle retrieve periodic meter reads for GAS response message in WS adapter
- [x] Implement scenarios handle retrieve periodic meter reads for GAS results ws request in WS adapter
- [ ] Implement acceptance tests
- [ ] Test

#### Scenarios

Scenario: Receive a retrieve periodic meter reads for GAS request
```
Given a retrieve periodic meter reads request from a client for a G meter for a given period
When the request is received
Then E Meter parent and the M-Bus channel on which  G meter is communicating should be determined
And the periodic meter reads should be retrieved from the device (data stored in parent E meter) and for the given period
And the periodic meter reads should be temporarily stored
And a periodic meter reads retrieved notification should be sent to the client
```
Scenario: Receive a get periodic meter reads results request
```
Given a get periodic meter reads results request from a client
When the request is received
Then the periodic meter reads result should be retrieved from temporary storage
And a response containing the periodic meter reads should be returned to the client
And a response containing the periodic meter reads should be returned to the client
And the temporarily stored periodic meter reads should be deleted
```

#### OSGP Functions
```
- request periodic GAS meter data:
  - parameters
    - DeviceIdentification of the GAS meter: alpha numeric maxlength 17
    - PeriodType: DAILY, MONTHLY (or INTERVAL see #228)
    - startDate: date
    - endDate: date
  - output
    - DeviceIdentification of the GAS meter: alpha numeric maxlength 17
    - CorrelationUid: alpha numeric minimal 20
- retrieve periodic GAS meter data:
  - parameters
    - DeviceIdentification of the GAS meter: alpha numeric maxlength 17
    - CorrelationUid: alpha numeric minimal 20
  - output (0 or more)
    - PeriodType: DAILY, MONTHLY (or INTERVAL see #228)
    - LogTime: datetime
    - consumption: long
    - captureTime: datetime
```

#### Device interface
```
Daily 
- Class: 7
- Logical name: 1-0:99.2.0.255
Monthly
- Class: 7
- Logical name: 0-0:98.1.0.255
```

#### Input:
```
- PeriodType: DAILY or MONTHLY (required)
- DeviceIdentification of the G meter (required) -> E Meter (parent) and M-bus channel (n) have to be determined
- Begin period (type: date (required))
- End period (type: date (required))
```
 
#### Response (0 or more):
```
- PeriodType: DAILY & MONTHLY
- LogTime: datetime, 
- M-Bus Value n Channel n:  long (whole number)
- Capture time channel n: datetime 
```

**Comment by eduarddrenth** [comment]
@elhachhouchi: is the gas value stored on the E-meter as a whole number (m3, no mantissa / fractional part)?
