### ISSUE TITLE
Retrieve actual meter reads GAS

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#227]
### Story
```
As a grid operator
I want OSGP to retrieve actual meter reads
So that I can provide the meter data to 3rd parties 
```
#### Tasks:
- [ ] Define acceptance criteria
- [x] Implement scenarios handle retrieve actual meter reads ws request in WS adapter
- [x] Implement scenarios handle retrieve actual meter reads request message in Domain adapter
- [x] Implement scenarios handle retrieve actual meter reads request message in Platform core
- [x] Implement scenarios handle retrieve actual meter reads request message in Protocol adapter
- [x] Implement scenarios handle retrieve actual meter reads response message in Platform core
- [x] Implement scenarios handle retrieve actual meter reads response message in Domain adapter
- [x] Implement scenarios handle retrieve actual meter reads response message in WS adapter
- [x] Implement scenarios handle retrieve actual meter reads results ws request in WS adapter
- [ ] Implement acceptance tests
- [ ] Test

#### Scenarios
Scenario: Receive a retrieve actual meter reads request
```
Given a retrieve actual meter reads request from a client for a G meter for a given period
When the request is received
Then E Meter parent and the M-Bus channel on which  G meter is communicating should be determined
And the actual meter reads should be retrieved from the device (data sorted in parent E meter)
And the actual meter reads should be temporarily stored
And a actual meter reads retrieved notification should be sent to the client
```
Scenario: Receive a get actual meter reads results request
```
Given a get actual meter reads results request from a client for a G meter
When the request is received
Then the actual meter reads result should be retrieved from temporary storage
the meter reads should be converted to m3
(conversion may be done in the scenario above: architecture choice!)
(the unit of the retrieved meter reads is already stored in OSGP )
And a response containing the actual meter reads should be returned to the client
And the temporarily stored actual meter reads should be deleted
```

#### OSGP Function
```
- request actual GAS meter reads:
  - input
    - DeviceIdentification of the GAS meter: alpha numeric maxlength 17
  - output
    - DeviceIdentification of the GAS meter: alpha numeric maxlength 17
    - CorrelationUid: alpha numeric minimal 20
- retrieve actual GAS meter reads:
  - input
    - DeviceIdentification of the GAS meter: alpha numeric maxlength 17
    - CorrelationUid: alpha numeric minimal 20
  - output (0 or 1)    
    - LogTime: datetime
    - consumption : decimal (9,3)
    - captureTime: datetime
```

#### Device interface
```
Class: 4
M-Bus Master Value 0-x:24.2.1.255  (x = M-bus channel)
``` 
#### Input:
```
•	DeviceIdentification of the G meter (required) -> E Meter (parent) and M-bus channel (n) have to be determined
```

#### Response:
```
•	LogTime: datetime
•	M-Bus Value n Channel n:  decimal (9,3) (unit =m3, conversion to m3 has to done)
•	Capture time channel n: datetime 
```

**Comment by eduarddrenth** [comment]
@elhachhouchi: do we need to administer extra info in order to retrieve GAS data from a smart meter? If yes exactly which info (e.g. M-BUS) and in which data format?

**Comment by eduarddrenth** [comment]
We need to know:

- to which smart meter a GAS meter is connected?
- to which channel is the GAS meter connected

the administration of this info is in a seperate user story (@elhachhouchi, @bvdzwet: which story?)

**Comment by eduarddrenth** [comment]
@elhachhouchi @bvdzwet @rlemmers willen jullie eens naar deze kijken

**Comment by Sander3003** [comment]
Please keep the conversations in english ;)

**Comment by rlemmers** [comment]
The user story is in an open source repository. We shouldn't refer to our private repositories. If changes in those repositories are needed, it means one or more user stories should be created for the private repositories as well.

I will discuss the format with @phoutman and @kevinsmeets. In the past, it was decided to use the given-when-then scenarios. If we deviate from that earlier decision, it should be a project decision not an individual's preference.

**Comment by eduarddrenth** [comment]
I'll create an extra user story for sss.

Main thing should be clear, understandable description of functionality, format is just an aid. For me that means describing functionality in readable human language with references to background info.

**Comment by eduarddrenth** [comment]
@elhachhouchi @phoutman question:

input for request here can be only the GAS meter id, corresponding smart meter id and channel wil be looked up

or input can be

GAS meter id, smart meter id and channel

Which is preferred? And do you agree on the output?

**Comment by eduarddrenth** [comment]
Discussed in and out with Abdel, GAS meter id only will do, response is agreed. Only the naming for the fields is a todo
