### ISSUE TITLE
Retrieve interval values GAS - hourly

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#228]
### Story
```
As a grid operator
I want OSGP to retrieve Interval Values for GAS
So that I can provide the meter data to 3rd parties
```
#### Tasks:
- [ ] Define acceptance criteria
- [x] Implement scenarios handle retrieve Interval Values for GAS ws request in WS adapter
- [x] Implement scenarios handle retrieve Interval Values for GAS request message in Domain adapter
- [x] Implement scenarios handle retrieve Interval Values for GAS request message in Platform core
- [x] Implement scenarios handle retrieve Interval Values for GAS request message in Protocol adapter
- [x] Implement scenarios handle retrieve Interval Values for GAS response message in Platform core
- [x] Implement scenarios handle retrieve Interval Values for GAS response message in Domain adapter
- [x] Implement scenarios handle retrieve Interval Values for GAS response message in WS adapter
- [x] Implement scenarios handle retrieve Interval Values for GAS results ws request in WS adapter
- [ ] Implement acceptance tests
- [ ] Test

#### Scenarios
Scenario: Receive a retrieve Interval Values for GAS request
```
Given a retrieve Interval Values request from a client for a G meter for a given period
When the request is received
Then E Meter parent and the M-Bus channel on which  G meter is communicating should be determined
And the Interval Values should be retrieved from the device (data sorted in parent E meter) for the given period (Start date + timestamp, End date +  timestamp)
And the Interval Values should be temporarily stored
And a Interval Values retrieved notification should be sent to the client
```
Scenario: Receive a get Interval Values results request
```
Given a get Interval Values results request from a client for a G meter
When the request is received
Then the Interval Values result should be retrieved from temporary storage
And the meter reads should be converted to m3 
(conversion may be done in the scenario above: architecture choice!)
(the unit of the retrieved meter reads is already stored in OSGP )
And a response containing the Interval Values should be returned to the client
And the temporarily stored Interval Values should be deleted
```

#### OSGP Function
```
- request interval GAS meter data:
  - input
    - DeviceIdentification of the GAS meter: alpha numeric maxlength 17
    - PeriodType: DAILY, MONTHLY (or INTERVAL see #228)
    - startDate: datetime
    - endDate: dateTime
  - output
    - DeviceIdentification of the GAS meter: alpha numeric maxlength 17
    - CorrelationUid: alpha numeric minimal 20
- retrieve interval GAS meter data:
  - input
    - DeviceIdentification of the GAS meter: alpha numeric maxlength 17
    - CorrelationUid: alpha numeric minimal 20
  - output (0 or more)
    - PeriodType: INTERVAL (or DAILY, MONTHLY see #225)
    - LogTime: datetime
    - consumption : decimal (9,3)
    - captureTime: datetime
```

#### Device interface
```
Class: 7
Generic profile 0-x:24.3.0.255  (x = M-bus channel)
``` 
#### Input:
```
•	PeriodType: Interval (HOURLY) (required)
•	DeviceIdentification of the G meter (required)
•	Begin period (type: datetime) (required)
•	End period (type: datetime) (required)
```

#### Response:
```
PeriodType: Interval (HOURLY)
•	LogTime: datetime
•	M-Bus Value n Channel n:  decimal (9,3) (unit =m3, conversion to m3 has to done)
•	Capture time channel n: datetime
•	AMR Profile status code M-Bus channel n: has a size of 1 byte 
```
