### ISSUE TITLE
find the smart meter and channel a GAS meter is connected to

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#236]
As a grid operator 
I want OSGP to be able to find the E-meter a G-meter is connected to and the M-Bus channel it uses.
So that OSGP adequately can address the G-meter data

This issue is a minimal start of a GAS meter administration. It is necessary for the implementation of GAS meter functions such as #225, #227 and #228. It only covers introduction of an entity that holds GAS meter information and a relation to a E-meter. Filling the table with data should be done manually for now. The installation process for GAS meters should lead to entries in this table.

#### Tasks:
- [x] Create a GasMeterDevice entity with 4 non null columns:
deviceIdentification (String 40, id), smartMeter (deviceId smartmeter String 40), channel (1, 2, 3 or 4) and wired (boolean)
- [x] Create a flyway script that creates the table for GasMeterDevice
- [x] Create a function that finds a GasMeterDevice by id (deviceIdentification)
- [ ] Create a webservice operation to find gas meters

**Comment by eduarddrenth** [comment]
@elhachhouchi @phoutman @bvdzwet 

some options for finding gas meters:

- introduce GetGasDevicesRequest that only returns gas meters in GetDevicesResponse
- (mis)use DeviceType in GetDevicesResponse to indicate Gas meter, reuse GetDevicesRequest
- redesign GetDevicesRequest and GetDevicesResponse to be generic for whatever device is found

Personally I vote for the third, we can also reconsider the paging mechanism then (offset/max instead of total pages to return)
