### ISSUE TITLE
Converting meter reads into uniform unit

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#247]
This story depends on story osgp/platform#249, which describes the storage of the scalers and units for a device.
```
```

### Story
```
As a grid operator
I want OSGP to return the meter reads (E/G ) in a uniform unit (kWh/m3).
So that I can provide meter data to 3rd parties in a uniform and correct unit
```
#### Tasks:
- [x] Define acceptance criteria
- [ ] Implement scenarios handle Converting meter reads into uniform unit
- [ ] Implement acceptance tests
- [ ] Test

#### Scenario: convert meter reads into uniform unit for energy register
```
Given a captured Meter Read
And the Meter Read is for an energy register
And the Meter Read is for a device with id 54321
And the Meter Read is for register "Active energy import (+A)"
When the captured Meter Read value is received in the domain layer
Then the Meter Read value is converted to kWh
and the Meter Read value is rounded to 3 decimals
and the conversion calculation uses the scaler and unit stored for the "Active energy import (+A)" register of device 54321
```

#### Scenario: convert meter reads into uniform unit for gas register
```
Given a captured Meter Read
And the Meter Read is for a gas register
And the Meter Read is for a device with id 54321
And the Meter Read is for register "M-Bus Master Value"
When the captured Meter Read value is received in the domain layer
Then the Meter Read value is converted to m3
and the Meter Read value is rounded to 3 decimals
and the conversion calculation uses the scaler and unit stored for the "M-Bus Master Value" register of device 54321
```

#### Meter Read registers to convert
```
Active energy import (+A) (Class ID: 3) 
Logical name: 1-0:1.8.0.255 
Converted to : kWh

Active energy import (+A) rate 1 (Class ID: 3) 
Logical name: 1-0:1.8.1.255
Converted to : kWh

Active energy import (+A) rate 2 (Class ID: 3) 
Logical name: 1-0:1.8.2.255
Converted to : kWh

Active energy export –A (Class ID: 3) 
Logical name: 1-0:2.8.0.255
Converted to : kWh

Active energy export (-A) rate 1 (Class ID: 3) 
Logical name: 1-0:2.8.1.255
Converted to : kWh

Active energy export (-A) rate 2 (Class ID: 3) 
Logical name: 1-0:2.8.2.255
Converted to : kWh

M-Bus Master Value (Class ID: 4) 
Logical name: 0-x:24.2.1.255 (x=channel number (1..4)
Converted to : m3
```

### Important note
This function has to be a generic function so that it can be used (in the future) to covert other captured register values than the ones below. 
For example to convert for Power Quality Registers (1-0:32.7.0.255 Instantaneous voltage L1)

**Comment by eduarddrenth** [comment]
@phoutman @elhachhouchi @bvdzwet 

We should design a general solution, taking into account:
- standardize on one unit?
- let users provide a unit and calculate?
- pass values as is together with their unit?
- where and when to determine units?
- provide a list of supported units?

**Comment by robindenadel** [comment]
waiting for https://github.com/OSGP/Platform/issues/249
