### ISSUE TITLE
Generate new keys

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#248]
### Story: Generate new keys
```
As a grid operator
I want OSGP to be able to generate new security keys 
So that OSGP can replace the old security keys with the new keys
```
#### Tasks:
- [ ] Define acceptance criteria
- [ ] Create a function to generate a new key pair (Authentication And Encryption Key) 
- [ ] Implement acceptance tests
- [ ] Test

```
- New keys have to be generated by using a Non-deterministic Random Bit Generators
      Authentication Algorithm : AES-GCM-128
      Encryption Algorithm : AES-GCM-128 and AES-128 for key wrapping

- The new keys must be generated only for E-meter. 
  A G-meter uses neither an authentication key nor an encryption key.
```

### Scenario: Generate new authentication and encryption keys
```
Given new meter with device id E9998000014122715
When a request for generating a new authentication and encryption key
Then generate new authentication and encryption key
```

**Comment by eduarddrenth** [comment]
This should work, at the time we have a key generator in place, gerateKeys  can use this with minimal effort

**Comment by rudidevries** [comment]
I have added a very simple example of how to generate such keys. 
https://github.com/OSGP/Protocol-Adapter-DLMS/commit/3de75dddc492f04ba4196cfeeea04975b91f97ea

I have only created a function that can generate a key, and it is not used in any way. There is no webservice method for it, as this is not described in the tasks (which it normally is). I believe further use of generating keys will be implemented by OSGP/Platform#128, the story for replacing keys?

@elhachhouchi can you confirm this was what you meant for this story, or if you did want a webservice method to be available for this?
