### ISSUE TITLE
Retrieve Scaler & Unit

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#249]
See comment of Eduard at the bottom for extra design info

### Story: Retrieve Scaler & Unit
```
As a Grid Operator
I want OSGP to retrieve the scaler and unit for meter registers in the same call that retrieves meter reads
so that OSGP can return meter data in a uniform way
```

#### Tasks:
- [ ] Define acceptance criteria
- [ ] Implement scenarios Retrieve Scaler & Unit from a device
- [ ] Implement acceptance tests
- [ ] Test

#### Registers for which to retrieve the Scaler and Unit
```
Active energy import (+A) (Class ID: 3) 
Logical name: 1-0:1.8.0.255 

Active energy import (+A) rate 1 (Class ID: 3) 
Logical name: 1-0:1.8.1.255 

Active energy import (+A) rate 2 (Class ID: 3) 
Logical name: 1-0:1.8.2.255 

Active energy export –A (Class ID: 3) 
Logical name: 1-0:2.8.0.255 

Active energy export (-A) rate 1 (Class ID: 3) 
Logical name: 1-0:2.8.1.255 

Active energy export (-A) rate 2 (Class ID: 3) 
Logical name: 1-0:2.8.2.255 

M-Bus Master Value (Class ID: 4) 
Logical name: 0-x:24.2.1.255 (x=channel number (1..4)
```

### Notes
- This function has to be generic, so we can use it in the future to store the Scaler & Unit for additional registers (objects). For example for Power Quality Registers (1-0:32.7.0.255 Instantaneous voltage L1).
- It's not needed to create a webservice operation. Retrieval of scaler and unit will be done as part of the retrieval of meter reads.

**Comment by eduarddrenth** [comment]
Table 4 – Examples for scaler_unit

|Value|Scaler|Unit|Data|
|---|---|---|---|
|263788|-3|m3|263,788 m3|
|593|3|Wh|593 kWh|
|3467|0|V|3467 V|

**definitions and design decisions:**

scaler: multiplier as a power of 10 (scaler = -2: times 0.01)
unit: for example kwh, wh, kw, w or m3

Osgp/platform dictates the units used and their data format.
For devices we need to know the unit(s) of the values stored and the scaler to apply to the values.

- unit (enum) en scaler will be stored in DlmsDevice in the protocol layer
- per device we use 1 combination of unit/scaler

- conversion of values to units and formats used in osgp/platform happens in the protocol layer (not for #249)
- we need at least good logging for the conversion, perhaps also a check by converting back and comparing with the original value (not for #249)

- no support yet for mbus devices (we do not have info for mbus devices in the protocol layer, solution in osgp/platform is temporary, design needed)
- no support yet for updating scaler/unit from integration layer
- no integration yet with the installation process

What will be built:

- enum with units in protocol layer
- dlms protocol function to retrieve and store unit and scaler
- fields unit (enum) and scaler in DlmsDevice

Testing will be done from a standalone client
