### ISSUE TITLE
Selective Access via jdlms library

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#253]
### Story
```
As Grid Operator
I want to be able to only retrieve certain values from a buffer with a "Profile generic"
So that I can be able to retrieve only the requested data from the meter 
(Basic principle : It is not allowed to retrieve data from the meter whithout authorization.)
```

#### Scenario: Using selective Access to only retrieve certain values from a buffer with a "Profile generic"
```
When we use selective access to only retrieve certain values from a buffer with 
a "Profile generic" instance we use:

1) a range descriptor where we narrow down the results returned based on a from/to 
value  for the clock :
This functionality WORKING WELL

2) We should also be able to use an array for selected_values where we can narrow 
down on the captured objects returned :
This functionality NOT YET WORKING)
```
#### Tasks:
- [ ] Define acceptance criteria
- [ ] Ask Fraunhofer Institute to implement Selective Acces correctly in jdlms library
- [ ] Install new version of the jdlms library
- [ ] Implement required changes to correctly use the new version of the jdlms library 
- [ ] Implement acceptance tests
- [ ] Test

**Comment by robindenadel** [comment]
@elhachhouchi can we close this item? We already use selective access where applicable.
