### ISSUE TITLE
Retrieve Security keys from OSGP platform

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#255]
### Story: Retrieve Security keys from OSGP platform
```
As a grid operator
I want to be able to retrieve security keys from the platform for a group of meters
So that the selected security keys can be delivered to requesting party
```

#### Tasks:
- [ ] Define acceptance criteria
- [ ] Implement scenarios handle Retrieve keys request in WS adapter
- [ ] Implement scenarios handle Retrieve keys request message in Domain adapter
- [ ] Implement scenarios handle Retrieve keys request message in Platform core
- [ ] Implement scenarios handle Retrieve keys request message in Protocol adapter
- [ ] Implement scenarios handle Retrieve keys response message in Platform core
- [ ] Implement scenarios handle Retrieve keys response message in Domain adapter
- [ ] Implement scenarios handle Retrieve keys response message in WS adapter
- [ ] Implement acceptance tests
- [ ] Test

#### Scenarios

Scenario: Handle retrieve security keys ws request 
```
Given a retrieve security keys request from a client
And the retrieve security keys request contains a list of device id <<<deviceid>>>
And the retrieve security keys request contains organisation id <<<organisationid>>>
When the retrieve security keys request is received 
Then requested security keys should be collected 
And requested security keys should be sent to requesting party
```

#### OSGP Function
```
Functie: Retrieve security Keys
Parameters: List of DeviceIdentification
```
#### Device interface
```
No communication with smart meter is required
```

#### Input:
```
- List of DeviceIdentification
```
 
#### Response:
```
- List of AuthenticationKey, EncryptionKey, MasterKey
```
