### ISSUE TITLE
Encryption key exchange on G meter

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#256]
### Story:  transfer user key into the M-Bus device
```
As a grid operator
I want to be able to transfer the user key into the M-Bus device
So that I can communicate in a secure manner with the G meter 
```

#### Tasks:
- [ ] Define acceptance criteria
- [ ] Implement scenarios handle transfer user key to G meter request in WS adapter
- [ ] Implement scenarios handle transfer user key to G meter request message in Domain adapter
- [ ] Implement scenarios handle transfer user key to G meter request message in Platform core
- [ ] Implement scenarios handle transfer user key to G meter request message in Protocol adapter
- [ ] Implement scenarios handle transfer user key to G meter response message in Platform core
- [ ] Implement scenarios handle transfer user key to G meter response message in Domain adapter
- [ ] Implement scenarios handle transfer user key to G meter response message in WS adapter
- [ ] Implement acceptance tests
- [ ] Test

#### Scenarios

Scenario: Handle transfer user key to G meter  ws request 
```
Given a transfer user key to G meter request from a client
And the transfer user key to G meter contains a device id <<<deviceid>>>
And the replace keys request contains organisation id <<<organisationid>>>
And the replace keys request contains the user key for G meter
When the transfer user key to G meter request is received 
Then a correlation id should be sent to the client 
And a connection with the E meter should be established
And the user key should be set on the G meter via the E meter
And a notification should be sent to the client
And the notification should contain the correlation id
```

#### OSGP Function
```
Functie: TransferUserKeyToMbus
Parameters: DeviceIdentification, User Key 
```
#### Device interface
```
See:
-	 DLMS Blue book
-	20140314 Dutch Smart Meter Requirements v4.2.2 Final P2.docx , paraphraf 6.5
```

#### Input:
```
- DeviceIdentification G-meter
- User key
```
 
#### Response:
```
- Meter response (OK, NOK)
```

**Comment by robindenadel** [comment]
1) The Mbus autoscan configuration is set on the E meter
2) After a scan by the E meter the G meter is detected
3) The E meter indicates to OSGP that a G meter is detected
4) OSGP tells the integration layer about the detection
5) The integration layer checks in the Asset administration whether or not the G meter belongs to the E meter 
6) If the meters G meter belongs to the E meter, the integration layer orders OSGP to send the G meter encryption key to the E meter
7) The E meter makes sure the encryption key is installed on the G meter
8) The E meter and G meter can communicate in a secure/encrypted way
