### ISSUE TITLE
Establish connection with wired G meter

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#259]
### Story
```
As a Grid Operator
I want to communicate with a G meter which is wired to an E meter
So that I am able to communicate with a wired G meter via the E meter
```

#### Tasks:
- [x] Define acceptance criteria
- [x] Establish a connection between a wired M-bus G meter and a E-meter 
- [x] Implement acceptance tests for a wired M-bus connection
- [x] Test wired connection

#### Scenario: retrieve interval meter reads from a G meter which is wired to an E meter
```
Given a G meter which is wired to an E meter
When a request is sent from a client to retrieve interval meter reads from  this G meter 
Then the interval meter reads have to be captured from the G meter, the same way as in:
USER STORY osgp/platform#225
```
