### ISSUE TITLE
Retrieve firmware version

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#261]
### Story
```
As a grid operator
I want to be able to get the firmeware version of a meter
So that I can see which software version is installed  on the meter 
```

#### Tasks:
- [ ] Define acceptance criteria
- [ ] Implement scenarios handle get firmeware version request in WS adapter
- [ ] Implement scenarios handle get firmeware version request message in Domain adapter
- [ ] Implement scenarios handle get firmeware version request message in Platform core
- [ ] Implement scenarios handle get firmeware version request message in Protocol adapter
- [ ] Implement scenarios handle get firmeware version response message in Platform core
- [ ] Implement scenarios handle get firmeware version response message in Domain adapter
- [ ] Implement scenarios handle get firmeware version response message in WS adapter
- [ ] Implement scenarios handle get firmeware version result request in WS adapter
- [ ] Implement acceptance tests
- [ ] Test

#### Scenarios

Scenario: get the firmeware version from device
```
Given a get firmeware version request from a client
And the get firmeware version request contains device id <<<deviceid>>>
And the get firmeware version request contains organisation id <<<organisationid>>>
And the get firmeware version request one single query action
When the get firmeware version request is received 
Then a correlation id should be sent to the client 
And a connection with the meter should be established
And the query action should be executed on the meter
And the query action result should be stored
And a notification should be sent to the client
And the notification should contain the correlation id
```

Scenario: Receive a get firmeware version result request from the client
```
Given a get firmeware version result request from a client
When the request is received
Then the firmeware version result should be retrieved from storage
And a response containing the firmeware version should be returned to the client
```

#### OSGP Functie
```
Functie: Get Firmeware version
Parameters: DeviceIdentification
```

#### Device interface (Check the objects in DMSR and DLMS)
```
Class: 1
OBIS-object 1-0:0.2.0.255 
Attribute: 2
<<<See DSMR/DLSM documentation >>>
```

#### Input:
```
•	DeviceIdentification (required)
```

#### Response:
```
•	Firmware version: Octet-string 
•	LogTime: datetime (time when the firmware version is captured from the meter)
```

**Comment by rlemmers** [comment]
"Help wanted" attached, because @elhachhouchi will check if this is needed for the first release.
