### ISSUE TITLE
Establish connection with wireless G meter

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#272]
### Story
```
As a Grid Operator
I want to communicate with a G meter which is wireless connected to an E meter
So that I am able to communicate with a wireless G meter via the E meter
```

There's no code to enable communication to a wireless G meter. We only need to realize a working physical setup (connection / configuration).

#### Tasks:
- [x] Define acceptance criteria
- [ ] Establish a connection between a wireless M-bus G meter and a E-meter 
- [ ] Implement acceptance tests for a wireless M-bus connection
- [ ] Test wireless connection

#### Scenario: retrieve interval meter reads from a G meter which is wireless connected to an E meter
```
Given a G meter which is wireless connected to an E meter
When a request is sent from a client to retrieve interval meter reads from  this G meter 
Then the interval meter reads have to be captured from the G meter, the same way as in:
USER STORY osgp/platform#225
```

**Comment by robindenadel** [comment]
1) The Mbus autoscan configuration is set on the E meter
2) After a scan by the E meter the G meter is detected
3) The E meter indicates to OSGP that a G meter is detected
4) OSGP tells the integration layer about the detection
5) The integration layer checks in the Asset administration whether or not the G meter belongs to the E meter 
6) If the meters G meter belongs to the E meter, the integration layer orders OSGP to send the G meter encryption key to the E meter
7) The E meter makes sure the encryption key is installed on the G meter
8) The E meter and G meter can communicate in a secure/encrypted way
