### ISSUE TITLE
Remove E meter

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#281]
### Story built out an E meter 
```
As a grid operator, after an E meter is physical built out from the field 
I want the Head-End to execute the build out by updating its meter administration
So that the meter administration in Head-End reflects the situation in the field
```

#### Tasks:
- [ ] Define acceptance criteria
- [ ] Implement scenarios handle built out an E meter request 
- [ ] Implement acceptance tests
- [ ] Test

#### Scenarios

Scenario: Handle a built out an E meter request from a client 
```
Given a built out an E meter request from a client
And the request contains a DeviceIdentification
When the request is received
Then a response with correlation id should be sent to client
And the meter administration has to be updated to reflect the situation on the field 
(change the status of the meter)
And a command executed notification should be sent to the client
```

#### OSGP Functie
```
Functie: Built out an E meter
Parameters: DeviceIdentification
```

#### Output
```
-	A meter built out notification
```
