### ISSUE TITLE
Store security keys

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#299]
### Story: Manage security keys
```
As a grid operator
I want OSGP to be able store the security keys (the currently used keys and the archived old ones) 
So that I can track the history of used security keys
and so that I can retrieve a list of currently used keys for field Engineers 
```
#### Tasks:
- [ ] Define acceptance criteria
- [ ] Implement scenarios Manage security keys
- [ ] Implement acceptance tests
- [ ] Test

#### Notes
- An E meter has three security keys: the master, authentication and encryption key
the master key is never replaced
- A G meter has only one security key: the user key
- A current security key has the field valid_from filled and valid_to empty

#### Scenario: Store initial security keys for an E meter
```
	Given a shipment file with delivery date 20150710
	And the shipment file contains a new E meter with device id E9998000014122715
	When the shipment file is processed
	Then the master, authentication and encryption key are stored with
	| device id 	| E9998000014122715 |
	| valid_from 	| 20150710			|
	| valid_to 		| null				|
```
#### Scenario: Store initial security key for a G meter
```
	Given a shipment file with delivery date 20150710 
	And the shipment file contains a G meter with device id G9998000014129485
	When the shipment file is processed
	Then the user key is stored with
	| device id 	| G9998000014129485 |
	| valid_from 	| 20150710			|
	| valid_to 		| null				|
```

**Comment by robindenadel** [comment]
Create a table security_key with a foreign key connection to smart_metering_device. The table contains the type of security key (master, encryption, authentication or user), the device_id and the valid_from and valid_to feilds

**Comment by rudidevries** [comment]
Pull requests have been created and are waiting for review ATM. Note that the scenario for the G meter has not been built, as the process for handling the shipmentfile is not built yet. (see osgp/platform#267)
