### ISSUE TITLE
Check active communication session

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Platform#309]
### Story: Check active communication session
```
As a Grid Operator
I want to be able to check if OSGP has an active communication session with a meter
So that I don’t have to send a wake up SMS to the meter if I want to send a request to the meter
```

#### Tasks:
- [ ] Define acceptance criteria
- [ ] Implement scenarios handle Check active communication session
- [ ] Implement acceptance tests
- [ ] Test

#### Scenario: Check if the meter has  active communication session
```
Given a request to be send to the meter
When a request needs to be send to device with id 54321
and device 54321 uses GPRS for communication
Then check first if the meter has an active communication session
