### ISSUE TITLE
Retrieve periodic meter reads E

### ISSUE THREAD

**Issue by rlemmers** [OSGP/Platform#43]
### Story: Retrieve periodic meter readings E
```
As a grid operator
I want OSGP to retrieve periodic meter readings
So that I can monitor the energy consumption
```
#### Scenario: Retrieve periodic meter readings E
```
Given a retrieve periodic meter readings request
When the request is received
Then the periodic meter readings should be retrieved
And the periodic meter readings should be temporarily stored
And a meter data retrieved notification should be sent
```
#### Scenario: Retrieve periodic meter readings results
```
Given a retrieve periodic meter readings results request
When the request is received
Then the periodic meter readings result should be sent 
And the temporarily stored periodic meter readings should be deleted
```

#### Tasks:
- [ ] Define acceptance criteria
- [ ] Create web services
- [x] Implement scenarios handle retrieve periodic meter readings ws request in WS adapter
- [x] Implement scenarios handle retrieve periodic meter readings request message in Domain adapter
- [x] Implement scenarios handle retrieve periodic meter readings request message in Platform core
- [ ] Implement scenarios handle retrieve periodic meter readings request message in Protocol adapter
- [x] Implement scenarios handle retrieve periodic meter readings response message in Platform core
- [x] Implement scenarios handle retrieve periodic meter readings response message in Domain adapter
- [x] Implement scenarios handle retrieve periodic meter readings response message in WS adapter
- [x] Implement scenarios handle retrieve periodic meter readings results ws request in WS adapter
- [ ] Implement acceptance tests
- [ ] Test

#### Scenario: Handle retrieve periodic meter readings ws request with a single E-meter query action from a client 
```
Given a retrieve periodic meter readings request from a client
And the request is for a device with id <<<deviceid>>>
And the request contains a single periodic meter readings query action
And the query action is of period type <<<periodtype:daily/monthly>>>
And the query action is for a date <<<date>>>

When the request is received

Then a retrieve periodic meter readings request message should be sent to the smart metering domain adapter
And the message should contain a deviceid <<<deviceid>>>
And the message should contain a single query action
And the action should be of type ...
And ...
```
```
Alternative scenarios:
- Multiple E-meter queries for different dates and/or period types
```
```
Exception scenarios:
- TBD
```

#### Scenario: Handle retrieve periodic meter readings request message from the smart metering ws adapter
```
Given a retrieve periodic meter readings request message from the smart metering ws adapter

When the message is received

Then the retrieve periodic meter readings request message should be sent to the core
```
```
Alternative scenarios:
- Multiple E-meter queries for different dates and/or period types
```
```
Exception scenarios:
- Device is not known
```

#### Scenario: Handle retrieve periodic meter readings request message from the smart metering domain adapter
```
Given
When
Then
```
```
Alternative scenarios:
- TBD
```
```
Exception scenarios:
- Organisation is not known
- Organisation is not authorised for the device
- Protocol is not known for the device
```

#### Scenario: Handle retrieve periodic meter readings request message from the core
```
Given
When
Then
```
```
Alternative scenarios:
- Multiple E-meter queries for different period types
```
```
Exception scenarios:
- Device is unreachable
```

#### Scenario: Handle retrieve periodic meter readings response message from the dsmr protocol adapter
```
Given
When
Then
```
```
Alternative scenarios:
- TBD
```
```
Exception scenarios:
- TBD
```

#### Scenario: Handle retrieve periodic meter readings response message from the core
```
Given
When
Then
```
```
Alternative scenarios:
- TBD
```
```
Exception scenarios:
- TBD
```

#### Scenario: Handle retrieve periodic meter readings response message from the smart metering domain adapter
```    
Given a retrieve periodic meter readings response message from the smart metering domain adapter
When the message is received
Then the periodic meter readings is temporarily stored
And a meter data retrieved notification should be sent to the client
And the notification should contain a correlation id
```
```
Alternative scenarios:
- TBD
```
```
Exception scenarios:
- TBD
```

#### Scenario: Handle retrieve periodic meter readings results ws request from a client
```
Given a retrieve periodic meter readings results ws request
And the request contains a correlation id <<<correlationid>>>

When the request is received

Then the temporary periodic meter readings results should be restored 
And a periodic meter results response should be sent to the client
And the response should contain correlation id <<<correlationid>>>
And the response should contain the periodic meter readings results
And the temporary periodic meter readings should be deleted
```
```
Alternative scenarios:
- TBD
```
```
Exception scenarios:
- TBD
```
